### ISSUE TITLE
14.0 Balance Forward now incorrect since latest merges in partner_statement

### ISSUE THREAD

**Issue by gdgellatly** [OCA/account-financial-reporting#1005]
@MiquelRForgeFlow I see you have been involved in these PR's, maybe you know better what has caused this rather major bug.
## Partner Statement
The name of the module that has a bug.

## Describe the bug
Recently Activity Statements received a number of PR's adjusting SQL. Somewhere this has broken and the balance forward now aggregates the balance forward for all companies, not just the company sending the statement.

## To Reproduce
**Affected versions**: 14.0

1. Have a partner shared between 2 companies with old invoices on each.
2. Print Activity Statement
3. Balance Forward is now the total, rather than being specific to company sending

**Expected behavior**
The old behaviour - Balance Forward is company specific

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by gdgellatly** [comment]
https://github.com/OCA/account-financial-reporting/blob/9d213e465d8a739c76ea769425d12d13583c10f7/partner_statement/report/activity_statement.py#L88

Also why this JOIN? we have company_id already, why join just to access the same id?

**Comment by gdgellatly** [comment]
https://github.com/OCA/account-financial-reporting/blob/629dd6c74e94aee43a45e2b540daf27ea8ad2a87/partner_statement/report/activity_statement.py#L106

Shouldn't this be Q3?

Also why the function re-assigning from Outstanding statement into Activity, couldn't we just have moved that into common?

**Comment by gdgellatly** [comment]
ref #988

**Comment by MiquelRForgeFlow** [comment]
> why this JOIN?

Yeah, I don't know. Maybe it was done this was due to a private customization, but not sure. It's true it could be simplified by doing:

```sql
FROM {sub}
WHERE {sub}.id = %(company_id)s
```

> Shouldn't this be Q3?

Yeah, that should fix this issue. Done in https://github.com/OCA/account-financial-reporting/pull/1006. Thanks

> couldn't we just have moved that into common?

No, I did that consciously. I didn't want too much methods in the common to be later replaced in the specific statement, or too much duplicated sqls. That's why I renamed them. Now ones are def _display_activity_xxx and the others are _display_outstanding_xxx, and both are in their corresponding file.

**Comment by gdgellatly** [comment]
@MiquelRForgeFlow We are getting customer complaints from everywhere regarding this PR. Now payments are no longer aggregated, balance end totals are wrong, amounts are wrong. I think we need to roll back that PR until we know what is going wrong. Such a big refactor rushed through in a week on a stable branch.

Right now I just got to fight fires in this chaos but will update issue once we discover more

\cc @JordiBForgeFlow

**Comment by gdgellatly** [comment]
I expect the balances problem is trying to use apr records. They have no date and they have always messed up statements for anything other than the most basic processes. Ever since v7.

**Comment by gdgellatly** [comment]
Before #988 :
![image](https://user-images.githubusercontent.com/5093264/217970180-f7af6bf6-d586-418d-9b5b-487dd86c8a87.png)
....
![image](https://user-images.githubusercontent.com/5093264/217970270-9b43500d-4109-4ea9-828f-baff2210669e.png)


After #988 :
![image](https://user-images.githubusercontent.com/5093264/217969787-e2244178-0e76-4bec-b5e5-23dd210f8c1c.png)
....
![image](https://user-images.githubusercontent.com/5093264/217969965-b7e4b191-52a7-46fa-b6b7-fde1e577b13b.png)

**Comment by MiquelRForgeFlow** [comment]
It's rare. This is after https://github.com/OCA/account-financial-reporting/pull/1006, right?

About payments being not aggregated... That part is not touched in https://github.com/OCA/account-financial-reporting/pull/988. That was changed a bit in https://github.com/OCA/account-financial-reporting/pull/967, where I changed a bit the "group by" in _display_activity_lines_sql_q1. Could you check if with https://github.com/OCA/account-financial-reporting/pull/1007 the aggregation issue is solved?

About the ending balances being wrong, it's strange. The https://github.com/OCA/account-financial-reporting/pull/988 only touched the initial balance. So, maybe it's consequence of the aggregation issue of the lines. Maybe gets solved when the aggregation issue it's solved. If not, I would need more data.

**Comment by gdgellatly** [comment]
I don't really know, I rolled 9 clients way back today. I don't think it is that rare, we have about 4000 wrong statements across 9 customers. I can't really look until Monday but we rolled everyone to 14.0.1.2.1 so it could be either.

**Comment by MiquelRForgeFlow** [comment]
> I can't really look until Monday

Hi. Have you checked?

**Comment by gdgellatly** [comment]
Hi,

Sorry we had a cyclone and floods. A few other priorities at the minute. I'll let end of month go by with known working code, then check.

**Comment by gdgellatly** [comment]
@MiquelRForgeFlow No it is still wrong, have rolled back again. The grouping issue seems fixed, but now the balances don;t match the again.

**Comment by gdgellatly** [comment]
It seems weird, I don't even understand why there is an applied amount on an Activity Statement, they are statements of activity and applied amounts make no sense in that context. That to me seems to be the problem, applied amounts just should not be there, it should be original amounts only.

but basically it seems you take a balance forward, and then ignore any application to prior balances, but don;t for activity during the month, so if an in month payment is reconciled against a prior month, then ending balances are wrong.

**Comment by MiquelRForgeFlow** [comment]
> then ending balances are wrong.

Hello @gdgellatly , I think I found what was wrong in your case. It was reported in https://github.com/OCA/account-financial-reporting/issues/1103, and I fixed in https://github.com/OCA/account-financial-reporting/pull/1164 😉
